src-d/identity-matching

- research/idmatching_literature.md
Signed-off-by: Waren Long <waren@sourced.tech>
After doing my Open Research Day, I ended up with a list useful papers on the topic. They are many so I made a brief description of them in few bullet points detailing my favorite contributions of each paper.
> Add a study of the literature around identity matching

- cmd/match-identities/main.go
- matching.go
- people.go
- people_test.go
- research/parquet2csv.py
Closes https://github.com/src-d/identity-matching/issues/49
> Set primary name to the most frequent

- Makefile
- external/bitbucket_test.go
- external/cached_matcher_test.go
- external/github_test.go
- external/gitlab_test.go
- matching_test.go
> Remove the test tokens

- matching.go
- people.go
> Post-review after primary names PR

- README.md
> Update the go report badge

- parquet2sql/parquet2sql.py
- parquet2sql/test_parquet2sql.py
Signed-off-by: Lou Marvin Caraig <loumarvincaraig@gmail.com>
> Fixes argument parsing in parquet2sql script

- matching.go
- reporter/reporter.go
> Handle empty results

- matching.go
> Fix the NaN stddev

- .travis.yml
> Remove the docker-test stage and fix deployment

- Makefile
> Change the docker image name

- Makefile
> Rename the docker image

- Makefile
> Build docker images with src-d/ci

- external/bitbucket.go
- external/cache.go
- external/cache_test.go
- external/github.go
- external/gitlab.go
- external/matcher.go
- matching_test.go
> Extend Matcher interface and make cache dumps incremental

- external/cache.go
- external/cache_test.go
> Cache the commit queires

- external/bitbucket.go
- external/bitbucket_test.go
- external/cache.go
- external/cache_test.go
- external/github.go
- external/github_test.go
- external/gitlab.go
- external/gitlab_test.go
- external/matcher.go
- matching.go
- matching_test.go
> Remove name detection from Matcher and implement GitHub's commit id

- matching_test.go
- people.go
- people_test.go
- tests/test_commits.sql
> Collect the commit hashes

- matching.go
- matching_test.go
> Enable experimental commit API

- research/bot_detection.py
Signed-off-by: Waren Long <waren@sourced.tech>
Related to https://github.com/src-d/identity-matching/issues/9
> Add Script to save bot detection model in asdf format

- cmd/match-identities/main.go
- external/cache.go
- matching.go
> Improve the logging

- external/cache.go
- external/cache_test.go
> Fix the cache deadlock

- .travis.yml
- cmd/match-identities/main.go
> Add the startup banner
